apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiremock-ni

configMapGenerator:
  - name: wiremock-ni-mappings-configs
    files:
      - mappings/root.json
      - mappings/getPersonInfoByMnfId-success.json
      - mappings/getPersonInfoByMnfId-empty-uuid.json
    options:
      labels:
        app: wiremock-ni
        component: mappings
      disableNameSuffixHash: true
  
  - name: wiremock-ni-responses-configs
    files:
      - responses/getPersonInfoByMnfId-success.json
      - responses/getPersonInfoByMnfId-empty-uuid.json
    options:
      labels:
        app: wiremock
        component: responses
      disableNameSuffixHash: true