apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiremock

configMapGenerator:
  - name: wiremock-ni-mappings-configs
    files:
      - ni/mappings/root.json
      # Add more mapping files here
    options:
      labels:
        app: wiremock-ni
        component: mappings
  
  - name: wiremock-ni-responses-configs
    files:
      - ni/responses/
      # This will include all files in the directory
    options:
      labels:
        app: wiremock-ni
        component: responses