apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiremock

configMapGenerator:
  - name: wiremock-ni-mappings-configs
    files:
      - root.json=mappings/root.json
      - getPersonInfoByMnfId-success.json=mappings/getPersonInfoByMnfId-success.json
      - getPersonInfoByMnfId-empty-uuid.json=mappings/getPersonInfoByMnfId-empty-uuid.json
    options:
      labels:
        app: wiremock-ni
        component: mappings
      disableNameSuffixHash: true
  
  - name: wiremock-ni-responses-configs
    files:
      - getPersonInfoByMnfId-success.json=responses/getPersonInfoByMnfId-success.json
      - getPersonInfoByMnfId-empty-uuid.json=responses/getPersonInfoByMnfId-empty-uuid.json
    options:
      labels:
        app: wiremock-ni
        component: responses
      disableNameSuffixHash: true