apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiremock

configMapGenerator:
  - name: wiremock-fawry-mappings-configs
    files:
      - mappings/
    options:
      labels:
        app: wiremock-fawry
        component: mappings
      disableNameSuffixHash: true
  
  - name: wiremock-fawry-responses-configs
    files:
      - responses/  # ← Use glob pattern for responses too
    options:
      labels:
        app: wiremock-fawry
        component: responses
      disableNameSuffixHash: true