apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiremock

configMapGenerator:
  - name: wiremock-fawry-mappings-configs
    files:
      - mappings/api-test.json
      - mappings/root.json
    options:
      labels:
        app: wiremock-fawry
        component: mappings
      disableNameSuffixHash: true
  
  - name: wiremock-fawry-responses-configs
    files:
      - responses/large-response.json
    options:
      labels:
        app: wiremock-fawry
        component: responses
      disableNameSuffixHash: true